import { spawn, type ChildProcess } from "node:child_process";
import fs from "node:fs/promises";
import { type BridgeConfig, socketAddress } from "./config.js";

export interface MediaMtxStatus {
  managed: boolean;
  running: boolean;
  apiReachable: boolean;
  configPath: string;
  lastError?: string;
}

export class MediaMtxManager {
  private child: ChildProcess | null = null;
  private lastError: string | undefined;

  constructor(private readonly config: BridgeConfig) {}

  async start(): Promise<void> {
    await fs.mkdir(this.config.runtimeDir, { recursive: true });
    await fs.writeFile(
      this.config.mediaMtxConfigPath,
      renderMediaMtxConfig(this.config),
      "utf8",
    );

    if (!this.config.manageMediaMtx) return;

    this.child = spawn(this.config.mediaMtxBinary, [this.config.mediaMtxConfigPath], {
      stdio: ["ignore", "pipe", "pipe"],
    });

    this.child.stdout?.on("data", (chunk) => {
      process.stdout.write(prefixLines("[mediamtx]", chunk.toString()));
    });
    this.child.stderr?.on("data", (chunk) => {
      process.stderr.write(prefixLines("[mediamtx]", chunk.toString()));
    });
    this.child.on("error", (err) => {
      this.lastError = err.message;
      // eslint-disable-next-line no-console
      console.warn(
        `[bridge] mediamtx process could not start: ${err.message}. ` +
          `Install mediamtx or set MEDIAMTX_BINARY/MEDIAMTX_MANAGE_PROCESS=false.`,
      );
    });
    this.child.on("exit", (code, signal) => {
      this.lastError =
        code === 0 ? undefined : `mediamtx exited code=${code} signal=${signal}`;
      this.child = null;
    });
  }

  async stop(): Promise<void> {
    const child = this.child;
    if (!child) return;
    child.kill("SIGINT");
    await new Promise<void>((resolve) => {
      const timer = setTimeout(() => {
        child.kill("SIGKILL");
        resolve();
      }, 4000);
      child.once("exit", () => {
        clearTimeout(timer);
        resolve();
      });
    });
  }

  async status(): Promise<MediaMtxStatus> {
    return {
      managed: this.config.manageMediaMtx,
      running: this.config.manageMediaMtx ? Boolean(this.child) : false,
      apiReachable: await this.isApiReachable(),
      configPath: this.config.mediaMtxConfigPath,
      lastError: this.lastError,
    };
  }

  private async isApiReachable(): Promise<boolean> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 800);
    try {
      const res = await fetch(
        `http://${this.config.mediaMtxApiHost}:${this.config.mediaMtxApiPort}/v3/config/global/get`,
        { signal: controller.signal },
      );
      return res.ok;
    } catch {
      return false;
    } finally {
      clearTimeout(timer);
    }
  }
}

function prefixLines(prefix: string, value: string): string {
  return value
    .split(/\r?\n/)
    .filter((line) => line.length > 0)
    .map((line) => `${prefix} ${line}\n`)
    .join("");
}

function yamlList(values: string[]): string {
  if (values.length === 0) return "[]";
  return `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;
}

export function renderMediaMtxConfig(config: BridgeConfig): string {
  return `# Generated by knoxnet-browser-cam bridge. Do not edit by hand.
logLevel: info
logDestinations: [stdout]
readTimeout: 10s
writeTimeout: 10s
writeQueueSize: 512

authMethod: internal
authInternalUsers:
- user: any
  pass:
  ips: []
  permissions:
  - action: publish
    path:
  - action: read
    path:
- user: any
  pass:
  ips: ['127.0.0.1', '::1']
  permissions:
  - action: api
  - action: metrics
  - action: pprof

api: yes
apiAddress: ${socketAddress(config.mediaMtxApiHost, config.mediaMtxApiPort)}
apiEncryption: no

rtsp: yes
rtspTransports: [udp, multicast, tcp]
rtspAddress: ${socketAddress(config.mediaMtxBindHost, config.mediaMtxRtspPort)}

rtmp: no
hls: no
srt: no

webrtc: yes
webrtcAddress: ${socketAddress(config.mediaMtxBindHost, config.mediaMtxWebRtcPort)}
webrtcEncryption: no
webrtcAllowOrigin: '*'
webrtcTrustedProxies: []
webrtcLocalUDPAddress: ${socketAddress(config.mediaMtxBindHost, config.mediaMtxWebRtcUdpPort)}
webrtcLocalTCPAddress: ''
webrtcIPsFromInterfaces: yes
webrtcIPsFromInterfacesList: []
webrtcAdditionalHosts: ${yamlList(config.mediaMtxAdditionalHosts)}
webrtcICEServers2: []
webrtcHandshakeTimeout: 10s
webrtcTrackGatherTimeout: 2s

paths:
  all_others:
    source: publisher
`;
}
